name: FAST
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python==3.9
  - numpy
  - torchaudio
  - torchvision
  - pytorch
  - scikit-image
  - tqdm
  - pip:
        - pyqt5==5.15.7
        - pyqt5-qt5==5.15.2
        - pyqt5-sip==12.11.0
        - csbdeep